language: cpp
sudo: false

matrix:
    include:
        - os: linux
          compiler: gcc-7
          addons: &gcc7
              apt:
                  sources:
                      - kalakris-cmake
                      - ubuntu-toolchain-r-test
                  packages:
                      - cmake
                      - g++-7
          env: CC=gcc-7 CXX=g++-7 STDLIB=libstdc++

install:
    - git clone --depth=1 https://github.com/simongog/sdsl-lite ${TRAVIS_BUILD_DIR}/sdsl/src
    - cd ${TRAVIS_BUILD_DIR}/sdsl/src
    - ./install.sh ${TRAVIS_BUILD_DIR}/sdsl/build

    - git clone --depth=1 https://github.com/google/benchmark.git ${TRAVIS_BUILD_DIR}/benchmark
    - git clone --depth=1 https://github.com/google/googletest.git ${TRAVIS_BUILD_DIR}/benchmark/googletest
    - cd ${TRAVIS_BUILD_DIR}/benchmark
    - mkdir build/
    - cd build/
    - cmake -DCMAKE_BUILD_TYPE=Release ../
    - make -j8
    - make test

    - git clone --depth=1 https://github.com/nixaraven/s9_vector ${TRAVIS_BUILD_DIR}/s9

before_script:
    - $CXX --version

jobs:
    include:
        - stage: unittest
          script:
              - cd ${TRAVIS_BUILD_DIR}/test
              - make
              - ./build/test-suite --reporter compact

        - stage: perftest
          script:
              - cd ${TRAVIS_BUILD_DIR}/perf
              - make
              - sudo bash run_tests.sh

stages:
    - compile
    - test
