language: cpp
dist: bionic
os: linux

jobs:
    include:
        - stage: unittest
          compiler: gcc-7
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - cmake
                      - g++-7
          env: CC=gcc-7 CXX=g++-7 STDLIB=libstdc++
          script:
              - cd ${TRAVIS_BUILD_DIR}/test
              - make
              - ./build/test-suite --reporter compact

install:
    - git clone --depth=1 https://github.com/simongog/sdsl-lite ${TRAVIS_BUILD_DIR}/sdsl/src
    - cd ${TRAVIS_BUILD_DIR}/sdsl/src
    - ./install.sh ${TRAVIS_BUILD_DIR}/sdsl/build

    - git clone --depth=1 https://github.com/google/benchmark.git ${TRAVIS_BUILD_DIR}/benchmark
    - git clone --depth=1 https://github.com/google/googletest.git ${TRAVIS_BUILD_DIR}/benchmark/googletest
    - cd ${TRAVIS_BUILD_DIR}/benchmark
    - mkdir build/
    - cd build/
    - cmake -DCMAKE_BUILD_TYPE=Release ../
    - make -j8
    - make test

    - git clone --depth=1 https://github.com/nixaraven/s9_vector ${TRAVIS_BUILD_DIR}/s9

before_script:
    - $CXX --version
